name: Run Playwright tests for IA and AA

on:
  pull_request:
    branches:
      - staging
  push:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Change directory to test project
        working-directory: ./penomo_tests
        run: echo "Now in test project folder"

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: penomo_tests/node_modules
          key: penomo-tests-${{ hashFiles('penomo_tests/package-lock.json') }}
          restore-keys: |
            penomo-tests-

      - name: Install dependencies
        working-directory: ./penomo_tests
        run: npm ci

      - name: Install Playwright browsers
        working-directory: ./penomo_tests
        run: npx playwright install --with-deps

      - name: Run Login tests
        working-directory: ./penomo_tests
        run: npx playwright test ./auth --project=chromium

      - name: Clear Playwright test results
        working-directory: ./penomo_tests
        run: rm -rf test-results

      - name: Run Playwright tests in Chromium
        working-directory: ./penomo_tests
        run: npx playwright test ./E2E --project=chromium

      # - name: Run Playwright tests in Chromium and save output
      #   id: run_tests
      #   run: |
      #     npx playwright test --project=chromium > result.log 2>&1
      #     echo "exit_code=$?" >> result.env
      #   shell: bash

      # - name: Run Playwright tests in Chromium
      #   run: npx playwright test --project=chromium

      # - name: Send Slack notification on test failure
      #   if: failure()  # тільки коли тести фейляться
      #   run: |
      #     curl -X POST -H 'Content-type: application/json' \
      #       --data '{"text":"Playwright tests failed on staging for Investor or Admin apps! Check the Allure report."}' \
      #       ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Install Allure CLI
        if: always()
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        if: failure()
        working-directory: ./penomo_tests
        run: npx allure generate allure-results -o allure-report --clean

      - name: Upload Allure report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: penomo_tests/allure-report
          retention-days: 3

      - name: Upload Allure raw results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: penomo_tests/allure-results
          retention-days: 3
